[package]
name = "QuickTransfer"
version = "0.1.0"
edition = "2021"

[dependencies]
argparse = "0.2.2"
bincode = "1.3.3"
serde = {version = "1.0.215", features = ["derive"] }
byteorder = "1.5.0"
colored = "2.1.0"
thiserror = "2.0.3"
rustyline = "15.0.0"